services:
  postgres-database:
    container_name: postgres-database
    image: postgis/postgis:latest
    environment:
      POSTGRES_DB: findyourdance
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: Fabian123!
      TZ: Europe/London
      PGTZ: Europe/London
    ports:
      - '6543:5432'
    volumes:
      - ./healthcheck.sh:/usr/local/bin/healthcheck.sh
      # - /etc/timezone:/etc/timezone:ro
      # - /etc/localtime:/etc/localtime:ro
    healthcheck:
      test:
        [
          'CMD-SHELL',
          'chmod +x /usr/local/bin/healthcheck.sh && /usr/local/bin/healthcheck.sh',
        ]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 15s

  auth:
    build:
      context: .
      dockerfile: ./apps/auth/Dockerfile
      target: development
    command: pnpm run start:dev auth
    environment:
      TZ: Europe/London
      NODE_TZ: Europe/London
    env_file:
      - ./apps/auth/.env
    ports:
      - '3000:3000'
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
      # - /etc/timezone:/etc/timezone:ro
      # - /etc/localtime:/etc/localtime:ro
    depends_on:
      postgres-database:
        condition: service_healthy

  qr-code-generator:
    build:
      context: .
      dockerfile: ./apps/qr-code-generator/Dockerfile
      target: development
    command: pnpm run start:dev qr-code-generator
    environment:
      TZ: Europe/London
      PGTZ: Europe/London
    env_file:
      - ./apps/qr-code-generator/.env
    ports:
      - '3001:3001'
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
      # - /etc/timezone:/etc/timezone:ro
      # - /etc/localtime:/etc/localtime:ro
    depends_on:
      postgres-database:
        condition: service_healthy

  address.api:
    build:
      context: .
      dockerfile: ./apps/address.api/Dockerfile
      target: development
    command: pnpm run start:dev address.api
    environment:
      TZ: Europe/London
      NODE_TZ: Europe/London
    env_file:
      - ./apps/address.api/.env
    ports:
      - '3002:3002'
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
      # - /etc/timezone:/etc/timezone:ro
      # - /etc/localtime:/etc/localtime:ro
    depends_on:
      postgres-database:
        condition: service_healthy

  events:
    build:
      context: .
      dockerfile: ./apps/events/Dockerfile
      target: development
    command: pnpm run start:dev events
    environment:
      TZ: Europe/London
      NODE_TZ: Europe/London
    env_file:
      - ./apps/events/.env
    ports:
      - '3003:3003'
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
      # - /etc/timezone:/etc/timezone:ro
      # - /etc/localtime:/etc/localtime:ro
    depends_on:
      postgres-database:
        condition: service_healthy
